Repository B2-200-OK/delivery_app, pull requests merged in 2024-06, with the labels that each got.

#12 feat : #8 / 메뉴 등록
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/StoreErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/GlobalNotFoundException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/StoreNotFoundException.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/response/MenuAddResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/entity/Menu.java
  src/main/java/com/sparta/delivery_app/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/store/repository/StoreRepository.java
Labels: ⭐️Feature

#11 Feat/1 회원가입
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/UserAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/controller/UserController.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/ConsumersSignupResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/UserSignupResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/entity/User.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: ⭐️Feature

#18 Feat/16 판매자 회원가입
  src/main/java/com/sparta/delivery_app/domain/user/controller/UserController.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ConsumersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ManagersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/ManagersSignupResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/entity/UserRole.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
Labels: ⭐️Feature

#20 Feat/14 메뉴수정
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/MenuErrorCode.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/response/MenuModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/entity/Menu.java
  src/main/java/com/sparta/delivery_app/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
Labels: ⭐️Feature

#24 Feat/3 매장등록
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/StoreErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/UserErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/StoreDuplicatedException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/UnableOpenStoreException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/UserNotExistException.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/store/controller/StoreController.java
  src/main/java/com/sparta/delivery_app/domain/store/dto/request/RegisterStoreRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/store/dto/request/RegistrateStoreRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/store/dto/response/RegisterStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/store/dto/response/RegistrateStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/store/entity/Store.java
  src/main/java/com/sparta/delivery_app/domain/store/entity/StoreStatus.java
  src/main/java/com/sparta/delivery_app/domain/store/repository/StoreRepository.java
  src/main/java/com/sparta/delivery_app/domain/store/service/StoreService.java
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/UserAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: ⭐️Feature

#34 Feat/9 좋아요 등록
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/LikedErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/LikedDuplicatedException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/LikedNotFoundException.java
  src/main/java/com/sparta/delivery_app/domain/liked/adaptor/LikedAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/liked/controller/LikedController.java
  src/main/java/com/sparta/delivery_app/domain/liked/dto/request/LikedRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/liked/dto/response/LikedResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/liked/entity/Liked.java
  src/main/java/com/sparta/delivery_app/domain/liked/repository/LikedRepository.java
  src/main/java/com/sparta/delivery_app/domain/liked/service/LikedService.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/UserAdaptor.java
Labels: ⭐️Feature

#40 feat : #15 메뉴 삭제 구현
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/entity/Menu.java
  src/main/java/com/sparta/delivery_app/domain/menu/entity/MenuStatus.java
  src/main/java/com/sparta/delivery_app/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
Labels: ⭐️Feature

#60 Feat/#39 회원 리뷰
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/ReviewErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewAccessDeniedException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewNotFoundException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewStatusException.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/UserReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/UserReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/UserReviewRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/UserReviewResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ReviewStatus.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/UserReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/UserReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
Labels: ⭐️Feature

#64 Feat/27 회원
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/OrderAccessDeniedException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/OrderNotFoundException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/PageNotFoundException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/StoreRegisteredHistoryException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/StoreStatusException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/global/GlobalAccessDeniedException.java
Labels: ⭐️Feature

#72 Fix/69 Review refactor
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewAccessDeniedException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewNotFoundException.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewStatusException.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/UserReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/UserReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
Labels: 🛠️Refactor

#73 Feat/70 프로필 수정
  src/main/java/com/sparta/delivery_app/domain/user/controller/UserController.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ConsumersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ManagersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/UserModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/UserModifyResponseDto/UserModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/entity/User.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
Labels: ⭐️Feature

#75 Refactor/66 menu
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/UserErrorCode.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
Labels: 🛠️Refactor

#77 61 feat 판매자 리뷰
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/ReviewErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/ReviewDuplicatedException.java
  src/main/java/com/sparta/delivery_app/domain/order/adaptor/OrderAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/ManagerReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/UserReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/ManagerReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/MangerReviewRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/ManagerReviewResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ManagerReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/ManagerReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/UserReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/service/MangerReviewsService.java
Labels: ⭐️Feature

#80 Feat/47 open api
  build.gradle
  src/main/java/com/sparta/delivery_app/common/config/SecurityConfig.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/PageErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/StoreErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/OpenApiAccessDeniedException.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/repository/MenuRepository.java
  src/main/java/com/sparta/delivery_app/domain/openApi/adapter/OpenApiAdapter.java
  src/main/java/com/sparta/delivery_app/domain/openApi/controller/OpenApiController.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/MenuListReadResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewListResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewPageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/StoreDetailsResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/StoreListReadResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/StorePageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/entity/OpenApi.java
  src/main/java/com/sparta/delivery_app/domain/openApi/repository/OpenApiRepository.java
  src/main/java/com/sparta/delivery_app/domain/openApi/service/OpenApiService.java
  src/main/java/com/sparta/delivery_app/domain/store/entity/StoreStatus.java
  src/main/java/com/sparta/delivery_app/rateLimit/BucketConfig.java
Labels: ⭐️Feature

#81 Feat/74 비밀번호 수정
  build.gradle
  src/main/java/com/sparta/delivery_app/TestDB.java
  src/main/java/com/sparta/delivery_app/common/config/SecurityConfig.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/JwtPropertiesErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/UserErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/security/AuthenticationUser.java
  src/main/java/com/sparta/delivery_app/common/security/AuthenticationUserService.java
  src/main/java/com/sparta/delivery_app/common/security/errorcode/GlobalSecurityException.java
  src/main/java/com/sparta/delivery_app/common/security/errorcode/SecurityErrorCode.java
  src/main/java/com/sparta/delivery_app/common/security/exception/SecurityException.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtLogoutHandler.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/AdminUserResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/request/MenuModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/store/entity/Store.java
  src/main/java/com/sparta/delivery_app/domain/token/service/TokenService.java
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/PasswordHistoryAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/UserAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/controller/UserController.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ConsumersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/ManagersSignupRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/UserPasswordModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/UserProfileModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/request/UserResignRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/UserModifyResponseDto/UserModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/dto/response/UserProfileModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/user/entity/PasswordHistory.java
  src/main/java/com/sparta/delivery_app/domain/user/entity/User.java
  src/main/java/com/sparta/delivery_app/domain/user/repository/PasswordHistoryRepository.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: ⭐️Feature

#84 feat : #76/merge to dev
  src/main/java/com/sparta/delivery_app/TestDB.java
Labels: ⭐️Feature

#88 feat : #86/testDB 수정
  src/main/java/com/sparta/delivery_app/TestDB.java
Labels: 🛠️Refactor

#92 Feat/55 매장별 다건 조회
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/controller/AdminStoreController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/controller/AdminUserController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/dto/AdminUserResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/UserReviewsRepository.java
Labels: 🛠️Refactor

#95 Refactor/90 menu refactor
  src/main/java/com/sparta/delivery_app/common/config/BucketConfig.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
  src/main/java/com/sparta/delivery_app/domain/openApi/adapter/OpenApiAdapter.java
  src/main/java/com/sparta/delivery_app/domain/openApi/controller/OpenApiController.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewListResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/entity/OpenApi.java
  src/main/java/com/sparta/delivery_app/domain/openApi/repository/OpenApiRepository.java
  src/main/java/com/sparta/delivery_app/domain/openApi/service/OpenApiService.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/store/service/StoreService.java
Labels: 🛠️Refactor

#99 feat : #98/리뷰 엔티티 재설정
  src/main/java/com/sparta/delivery_app/TestDB.java
  src/main/java/com/sparta/delivery_app/domain/order/entity/Order.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ManagerReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/UserReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/service/ManagerReviewsService.java
Labels: 🛠️Refactor

#106 Feat/104 주문 상태 변경
  src/main/java/com/sparta/delivery_app/domain/order/controller/OrderController.java
  src/main/java/com/sparta/delivery_app/domain/order/entity/Order.java
  src/main/java/com/sparta/delivery_app/domain/order/service/OrderService.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/UserReviews.java
Labels: ⭐️Feature

#110 Refactor/89 refactor 시큐리티
  src/main/java/com/sparta/delivery_app/common/config/SecurityConfig.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/JwtPropertiesErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/sparta/delivery_app/common/security/AuthenticationUserService.java
  src/main/java/com/sparta/delivery_app/common/security/errorcode/SecurityErrorCode.java
  src/main/java/com/sparta/delivery_app/common/security/exception/CustomSecurityException.java
  src/main/java/com/sparta/delivery_app/common/security/exception/SecurityException.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtLogoutHandler.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/delivery_app/domain/token/service/TokenService.java
Labels: 🛠️Refactor

#117 Refactor/100 회원 리뷰 등록
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewPageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/UserReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/UserReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/UserReviewAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/UserReviewModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/UserReviewRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/UserReviewAddResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/UserReviewModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ManagerReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ReviewStatus.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/UserReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/service/ManagerReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
Labels: 🛠️Refactor

#122 93 feat 특정매장 전체리뷰 조회
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/controller/AdminStoreController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/ReviewPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/review/adaptor/ManagerReviewsAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/ManagerReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/UserReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/store/controller/StoreController.java
  src/main/java/com/sparta/delivery_app/domain/store/entity/Store.java
Labels: ⭐️Feature

#121 Refactor/113 open api menu
  src/main/java/com/sparta/delivery_app/common/config/BucketConfig.java
  src/main/java/com/sparta/delivery_app/domain/menu/adaptor/MenuAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/menu/controller/MenuController.java
  src/main/java/com/sparta/delivery_app/domain/menu/dto/response/MenuAddResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/menu/entity/Menu.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
  src/main/java/com/sparta/delivery_app/domain/openApi/adapter/OpenApiAdapter.java
  src/main/java/com/sparta/delivery_app/domain/openApi/controller/OpenApiController.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewPageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/StorePageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/service/OpenApiService.java
  src/main/java/com/sparta/delivery_app/domain/order/service/OrderService.java
  src/main/java/com/sparta/delivery_app/domain/review/repository/UserReviewsRepository.java
  src/main/java/com/sparta/delivery_app/domain/store/repository/StoreRepository.java
Labels: 🛠️Refactor

#124 refactor : #112/ 파라미터 final 적용
  src/main/java/com/sparta/delivery_app/domain/user/adaptor/UserAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/user/controller/UserController.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
Labels: 🛠️Refactor

#116 Refactor/108 관심 매장
  src/main/java/com/sparta/delivery_app/common/exceptionhandler/ApiExceptionHandler.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/controller/AdminStoreController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/commen/page/util/PageUtil.java
  src/main/java/com/sparta/delivery_app/domain/liked/adaptor/LikedAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/liked/controller/LikedController.java
  src/main/java/com/sparta/delivery_app/domain/liked/repository/LikedRepository.java
  src/main/java/com/sparta/delivery_app/domain/liked/service/LikedService.java
  src/main/java/com/sparta/delivery_app/domain/openApi/controller/OpenApiController.java
  src/main/java/com/sparta/delivery_app/domain/openApi/service/OpenApiService.java
  src/main/java/com/sparta/delivery_app/domain/order/adaptor/OrderAdaptor.java
  src/main/java/com/sparta/delivery_app/domain/order/controller/OrderController.java
  src/main/java/com/sparta/delivery_app/domain/order/entity/Order.java
  src/main/java/com/sparta/delivery_app/domain/order/entity/OrderItem.java
  src/main/java/com/sparta/delivery_app/domain/order/service/OrderService.java
  src/main/java/com/sparta/delivery_app/domain/store/adaptor/StoreAdaptor.java
Labels: 🛠️Refactor

#125 Refactor/118 사장님 리뷰
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/OrderErrorCode.java
  src/main/java/com/sparta/delivery_app/common/exception/errorcode/ReviewErrorCode.java
  src/main/java/com/sparta/delivery_app/common/globalcustomexception/OrderStatusException.java
  src/main/java/com/sparta/delivery_app/domain/order/entity/OrderStatus.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/ManagerReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/ManagerReviewAddRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/ManagerReviewModifyRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/request/ManagerReviewRequestDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/ManagerReviewAddResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/dto/response/ManagerReviewModifyResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/ManagerReviews.java
  src/main/java/com/sparta/delivery_app/domain/review/service/ManagerReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
Labels: 🛠️Refactor

#129 refactor : #128/ 재발급 버그 수정
  src/main/java/com/sparta/delivery_app/domain/token/service/TokenService.java
Labels: 🐞BugFix

#131 Feat/123 판매 총 금액 다건 조회
  src/main/java/com/sparta/delivery_app/common/config/SecurityConfig.java
  src/main/java/com/sparta/delivery_app/common/security/AuthenticationUserService.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/delivery_app/common/security/jwt/JwtLogoutHandler.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/controller/AdminStoreController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageMenuPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageReviewPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageTotalPricePerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/ReviewPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/TotalPricePerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/service/AdminUserService.java
  src/main/java/com/sparta/delivery_app/domain/liked/adapter/LikedAdapter.java
  src/main/java/com/sparta/delivery_app/domain/liked/service/LikedService.java
  src/main/java/com/sparta/delivery_app/domain/menu/adapter/MenuAdapter.java
  src/main/java/com/sparta/delivery_app/domain/menu/service/MenuService.java
  src/main/java/com/sparta/delivery_app/domain/openApi/adapter/OpenApiAdapter.java
  src/main/java/com/sparta/delivery_app/domain/order/adapter/OrderAdapter.java
  src/main/java/com/sparta/delivery_app/domain/order/adapter/OrderItemAdapter.java
  src/main/java/com/sparta/delivery_app/domain/order/repository/OrderItemRepository.java
  src/main/java/com/sparta/delivery_app/domain/order/service/OrderService.java
  src/main/java/com/sparta/delivery_app/domain/review/adapter/ManagerReviewsAdapter.java
  src/main/java/com/sparta/delivery_app/domain/review/adapter/UserReviewsAdapter.java
  src/main/java/com/sparta/delivery_app/domain/review/service/ManagerReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/store/adapter/StoreAdapter.java
  src/main/java/com/sparta/delivery_app/domain/store/service/StoreService.java
  src/main/java/com/sparta/delivery_app/domain/token/service/TokenService.java
  src/main/java/com/sparta/delivery_app/domain/user/adapter/PasswordHistoryAdapter.java
  src/main/java/com/sparta/delivery_app/domain/user/adapter/UserAdapter.java
  src/main/java/com/sparta/delivery_app/domain/user/service/UserService.java
Labels: ⭐️Feature

#134 Refactor/132 관리자 페이징 처리 test
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageMenuPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageReviewPerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/PageTotalPricePerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/dto/TotalPricePerStoreResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/commen/page/util/PageUtil.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/ReviewPageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/dto/StorePageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/openApi/service/OpenApiService.java
  src/main/java/com/sparta/delivery_app/domain/order/dto/response/OrderPageResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/order/service/OrderService.java
Labels: 🛠️Refactor

#136 refactor: #135/관리자 회원 목록 조회 페이징
  src/main/java/com/sparta/delivery_app/domain/admin/adminstore/service/AdminStoreService.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/controller/AdminUserController.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/dto/AdminUserResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/dto/PageAdminUserResponseDto.java
  src/main/java/com/sparta/delivery_app/domain/admin/adminuser/service/AdminUserService.java
  src/main/java/com/sparta/delivery_app/domain/store/controller/StoreController.java
Labels: 🛠️Refactor

#140 fix : #118/ 리뷰 리펙토링
  README.md
  src/main/java/com/sparta/delivery_app/domain/order/adapter/OrderAdapter.java
  src/main/java/com/sparta/delivery_app/domain/order/repository/OrderRepository.java
  src/main/java/com/sparta/delivery_app/domain/review/adapter/UserReviewsAdapter.java
  src/main/java/com/sparta/delivery_app/domain/review/controller/ManagerReviewsController.java
  src/main/java/com/sparta/delivery_app/domain/review/service/ManagerReviewsService.java
  src/main/java/com/sparta/delivery_app/domain/review/service/UserReviewsService.java
  src/main/resources/application.yml
Labels: 🛠️Refactor

#141 Refactor/137 s3 파일명 수정
  README.md
  src/main/java/com/sparta/delivery_app/TestDB.java
  src/main/java/com/sparta/delivery_app/domain/review/entity/UserReviews.java
  src/main/java/com/sparta/delivery_app/domain/s3/service/S3Uploader.java
  src/main/java/com/sparta/delivery_app/domain/s3/util/S3Utils.java
Labels: 🛠️Refactor
